# Generated by Django 5.1.7 on 2025-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_users_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], max_length=20),
        ),
    ]
